# Created using winget CLI
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json

PackageIdentifier: ashavijit.hookrunner
PackageVersion: 0.26.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
