# Created using winget CLI
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: ashavijit.hookrunner
PackageVersion: 0.45.0
MinimumOSVersion: 10.0.0.0
InstallerType: portable
Commands:
  - hookrunner
UpgradeBehavior: install
ReleaseDate: 2024-12-19
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/ashavijit/HookRunner/releases/download/v0.45.0/hookrunner-windows-amd64.exe
    InstallerSha256: 716F37EE95D5978D9F2BE2A6546738D0688FA58CB09F6BAE5804C7334392634E
  - Architecture: arm64
    InstallerUrl: https://github.com/ashavijit/HookRunner/releases/download/v0.45.0/hookrunner-windows-arm64.exe
    InstallerSha256: 8FDFF47DE438066BCC77F88D1031A9FF8BA530C97DD078CADDD73063074FDADA
ManifestType: installer
ManifestVersion: 1.6.0
